// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcjrtkfnempqatvbrqrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjanJ0a2ZuZW1wcWF0dmJycXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzA0MjQsImV4cCI6MjA2MjA0NjQyNH0.Yftey4dJ77ATPQ0aocqjM-Im0GWt8if5oPtlu4FLo9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});